name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        VPS_SERVER_NAME: ${{ secrets.VPS_SERVER_NAME }}
        VPS_USER_NAME: ${{ secrets.VPS_USER_NAME }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.VPS_USER_NAME }}@${{ env.VPS_SERVER_NAME }} "
        mkdir -p /home/${{ env.VPS_USER_NAME }}/deployed_project &&
        cd /home/ubuntu/project/hw6_backend &&
        git pull origin main &&
        echo 'Deployment completed!'"
